### ISSUE TITLE
Certified Plugins - Integration Roadmap

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/HOOBS#97]
- [x] [@HOOBS/Wink ](https://github.com/hoobs-org/homebridge-wink/blob/master/README.md)

- [x] [@HOOBS/Nest](https://github.com/hoobs-org/homebridge-nest/blob/master/README.md) 
- [x] [@HOOBS/Chamberlain ](https://github.com/hoobs-org/homebridge-chamberlain/blob/master/README.md)
- [x] [@HOOBS/Google Home](https://github.com/hoobs-org/homebridge-google/blob/master/README.md)

**Comment by mkellsy** [comment]
We need to look into what this plugin does
homebridge-roku
It attempts to modify your config file.

**Comment by mkellsy** [comment]
We also need to test these plugins
homebridge-broadlink-rm
homebridge-platform-wemo
homebridge-tplink-smarthome
homebridge-webos-tv

**Comment by mkellsy** [comment]
Need to review this plugin
homebridge-roomba-stv

It has a wired command it needs to run to get access to a device. Need to combine the command.
From issue #139

**Comment by xdmate** [comment]
I'd love to have to have the Hive forever plugin on the roadmap, but as it currently is broken and the dev is MIA, I don't know how likely that is haha. I think Wemo would be a great addition, though. :D

**Comment by mkellsy** [comment]
I added homebridge-platform-wemo to the list, it is a solid plugin.

As for Give. We will need to discuss it. With the original developer MIS, we would have to take over the project. The good news is we can do that, the bad news is we scope our plugin's and vanilla Homebridge can't install scoped plugins.

**Comment by xdmate** [comment]
Ah I see. I'm surprised more people don't use Hive, as I believe it's very popular in the UK because British gas offers it with their service. Anyway, thanks for the awesome work!

**Comment by mkellsy** [comment]
The homebridge-sonoff plugin is overloading the platform config. It needs to be re-wrote to use the accessories section. This would make it easier to configure too.

**Comment by xdmate** [comment]
> I added homebridge-platform-wemo to the list, it is a solid plugin.
> 
> As for Hive. We will need to discuss it. With the original developer MIA, we would have to take over the project. The good news is we can do that, the bad news is we scope our plugin's and vanilla Homebridge can't install scoped plugins.

Hey after researching both the Hive_forever plugin and the other one thats on github I learned they're not broken. The API they used in their plugins is from British Gas, and I assume that's why it doesn't work for me, because I have Hives new Active heating and cooling thermostat. If you guys did take over development do you think theres a way you can get it working in the US? 
Hope I'm not bothering you, I just really want Homekit integrated, lol.
Thanks!

**Comment by magnificent3** [comment]
If i just could add homebridge-mi-hygrothermograph since it requires Noble. These libraries and their dependencies are required by the Noble library and provide access to the kernel Bluetooth subsystem.

**Comment by florian-muc** [comment]
Hi,
not sure this belongs here, but I currently (on 3.0.0 beta 67) have trouble getting the following plug-ins to install at all:
* homebridge-fritz
* homebridge-yamaha-avr
When trying to install them, there is progress display, but at the end they just don't show up.
So, if those could be "officially supported" (or working at all) I'd be very happy.
Thanks!

**Comment by florian-muc** [comment]
Created #213 and #214

**Comment by themick4u** [comment]
I'd wish to see the following in the future if possible (I currently am running and all but the dummy switches seem to work very well. The dummy switches homekit automations seem to need to be recreated many times):
homebridge-dummy (0.4.1)
homebridge-magichome (0.3.0)
homebridge-camera-ffmpeg (0.1.14)
homebridge-tuya-web (0.1.7)

Thanks for the fantastic work folks!

**Comment by askovi** [comment]
homebridge-nest-cam should be added alongside Nest. It currently requires a manual request of the access_token using a POST request curl. This should be automated but the plugin works well and is in high demand.

**Comment by mkellsy** [comment]
Look into this plugin too
https://www.npmjs.com/package/homebridge-gpio-device

**Comment by mkellsy** [comment]
If your issue was deleted, it is because the plugin has been moved into the main list, or is part of another issue.

**Comment by zgmorris13** [comment]
I’d love to see Kuna Maximus smart security light be added!

**Comment by BobbySlope** [comment]
homebridge-ikea-tradfri-gateway -> @hoobs/ikea-tradfri >work in progress<
https://github.com/hoobs-org/HOOBS/issues/303

**Comment by bjwgorman** [comment]
Hello. I would really like the Logitech remote supported. I have seen it is already available for Homebridge but not Hoobs.

https://www.npmjs.com/package/homebridge-harmonyhub

https://www.npmjs.com/package/homebridge-harmony

**Comment by maoten2000** [comment]
Add Crestron integration to roadmap please

**Comment by sivartyeldud** [comment]
Please add SimpliSafe for Hoobs roadmap.

https://www.npmjs.com/package/homebridge-simplisafe-security-system
https://www.npmjs.com/package/homebridge-simplisafe3

**Comment by BobbySlope** [comment]
> Add Crestron integration to roadmap,
> https://github.com/songzh96/homebridge-crestron/blob/master/README-ZhCN.md

Will not be Certified, Chinese Product and no way to Test it.

**Comment by jeroen1973** [comment]
Homewizard integration as certified pluginn would be nice!

**Comment by kwalb** [comment]
InsteonLocal integration as certified plugin would be appreciated, that and Plex v2

**Comment by AlexanderBabel** [comment]
Hey,

the Homebridge-broadlink plugin is no longer maintained. But I created a fork and implemented the tv features released in iOS 12.2 and currently this plugin in maintained by another contributor and part wise by me.

Check is out: https://github.com/AlexanderBabel/homebridge-broadlink-rm

**Comment by OptoAdmin** [comment]
I'd vote for myQ garage opener integration.

**Comment by mkellsy** [comment]
Please also certifie the plugin for Dyson Fans and the Dyson Vacuum Robot.

**Comment by quizatsaderac** [comment]
hello, 
Could you integrate this git : https://github.com/benoit-tk/homebridge_thekeys
thanks.

**Comment by askovi** [comment]
Please certify plugin homebridge-twinkly: https://www.npmjs.com/package/homebridge-twinkly

**Comment by d0n4v4nb3ck3r** [comment]
Please certify plugin homebridge-ecoplug https://www.npmjs.com/package/homebridge-ecoplug

**Comment by apexad** [comment]
Please certify homebridge-mysmartblinds-bridge: https://www.npmjs.com/package/homebridge-mysmartblinds-bridge

**Comment by quizatsaderac** [comment]
please certify plugin node-red-contrib-thekey : https://www.npmjs.com/package/node-red-contrib-thekey

**Comment by mkellsy** [comment]
homebridge-ecoplug

**Comment by BobbySlope** [comment]
Plugin Roadmap is now located in this [Projectboard](https://github.com/hoobs-org/HOOBS/projects/6)

If your comment is/was deleted we added the Plugin to the certified Plugins Projectboard

**Comment by JTDeel** [comment]
Please certify homebridge-vivint-fixed (approved by @askovi)

**Comment by inforatio** [comment]
Please certify homebridge-skybell

**Comment by BobbySlope** [comment]
@inforatio can u provide us a short tutorial on how to configure this plugin correctly?

**Comment by nicoduj** [comment]
Hi, Can you certify my harmony plugin ? https://github.com/nicoduj/homebridge-harmony/

**Comment by chongkwongsheng** [comment]
Please certify homebridge-ambiclimate

**Comment by nathancleary** [comment]
Has anybody worked out a plug-in for Neos Smartcam? For the UK market this would be beneficial, thanks.
